name: hello  yml
run-name: ${{ github.actor }} is running hello
on: [push]
jobs:
  job-name:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: echo "hello world"
     
