name: hello  yml
run-name: ${{ github.actor }} is running hello
on: [push]
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: "hello world"
     
